### ISSUE TITLE
Cannot use Generator With Latest NodeJS or NVM (with 4.5.0)

### ISSUE THREAD

**Issue by ghost** [wet-boew/generator-wet-boew-theme#32] opened 2016-11-09 23:12 UTC
Here is a log of the issue: [npm-debug.txt](https://github.com/wet-boew/generator-wet-boew-theme/files/582142/npm-debug.txt). I've been getting this issue on three different computers.

**Comment by kodecount** [comment] 2016-11-10 18:04
@masterbee @LaurentGoderre @nschonni @pjackson28

**Comment by nschonni** [comment] 2016-11-10 21:47
I believe grunt-sass needs to be updated here https://github.com/wet-boew/generator-wet-boew-theme/blob/master/app/templates/_package.json#L28 to support the newer platforms. There is also probably some drift in this package since some build tools have change in the wet core (JSHint -> Eslint, SCCSLint -> sass-lint, etc...)

**Comment by RobJohnston** [comment] 2016-11-11 12:39
I just tried the same thing and also bombed-out with sass.  Versions are node 6.9.1 and sass 0.7.0.

It appears that node 6 support was [added in sass v3.7.0](https://github.com/sass/node-sass/releases/tag/v3.7.0).

```
<snip>
gyp http GET http://nodejs.org/dist/v6.9.1/node-v6.9.1.tar.gz
gyp http 200 http://nodejs.org/dist/v6.9.1/node-v6.9.1.tar.gz
gyp http GET http://nodejs.org/dist/v6.9.1/node.lib
gyp http GET http://nodejs.org/dist/v6.9.1/x64/node.lib
gyp http GET http://nodejs.org/dist/v6.9.1/node.lib
gyp http GET http://nodejs.org/dist/v6.9.1/x64/node.lib
gyp http 404 http://nodejs.org/dist/v6.9.1/x64/node.lib
gyp WARN install got an error, rolling back install
gyp http 404 http://nodejs.org/dist/v6.9.1/node.lib
gyp http 404 http://nodejs.org/dist/v6.9.1/x64/node.lib
gyp http 404 http://nodejs.org/dist/v6.9.1/node.lib
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 64-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Users\Rob\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\install.js:313:20)
gyp ERR! stack     at emitOne (events.js:101:20)
gyp ERR! stack     at Request.emit (events.js:188:7)
gyp ERR! stack     at Request.onResponse (C:\Users\Rob\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:832:10)
gyp ERR! stack     at ClientRequest.g (events.js:291:16)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rob\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Rob\Projects\wet_test\node_modules\grunt-sass\node_modules\node-sass
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
Build failed
npm ERR! node-sass@0.7.0 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@0.7.0 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 10.0.14393
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rob\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Rob\Projects\wet_test
npm ERR! node -v v6.9.1
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Rob\Projects\wet_test\npm-debug.log
npm ERR! not ok code 0
```

**Comment by RobJohnston** [comment] 2016-11-11 13:56
Same error with node v4, and degrading further to node v0.12 produces a MSBUILD error (but again with sass), so there's no way forward (at least not on Windows 64-bit):

```
c:\Users\Rob\Projects\wet_test\node_modules\grunt-sass\node_modules\node-sass>node "C:\Users\Rob\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp http GET http://nodejs.org/dist/v0.12.17/node-v0.12.17.tar.gz
gyp http 200 http://nodejs.org/dist/v0.12.17/node-v0.12.17.tar.gz
gyp http GET http://nodejs.org/dist/v0.12.17/x64/node.lib
gyp http GET http://nodejs.org/dist/v0.12.17/node.lib
gyp http GET http://nodejs.org/dist/v0.12.17/node.lib
gyp http GET http://nodejs.org/dist/v0.12.17/x64/node.lib
gyp http 200 http://nodejs.org/dist/v0.12.17/x64/node.lib
gyp http 200 http://nodejs.org/dist/v0.12.17/node.lib
gyp http 200 http://nodejs.org/dist/v0.12.17/node.lib
gyp http 200 http://nodejs.org/dist/v0.12.17/x64/node.lib
child_process: customFds option is deprecated, use stdio instead.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "12.0", "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Rob\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "node" "C:\\Users\\Rob\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\Rob\Projects\wet_test\node_modules\grunt-sass\node_modules\node-sass
gyp ERR! node -v v0.12.17
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
Build failed
npm ERR! node-sass@0.7.0 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@0.7.0 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 10.0.14393
npm ERR! command "node" "C:\\Users\\Rob\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Users\Rob\Projects\wet_test
npm ERR! node -v v0.12.17
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\Users\Rob\Projects\wet_test\npm-debug.log
npm ERR! not ok code 0

```

**Comment by kodecount** [comment] 2016-11-12 13:14
@nschonni @RobJohnston Node-sass is also failing on Ubuntu 16.04 LTS 64-bit

**Comment by LaurentGoderre** [comment] 2016-11-14 13:46
This is terribly outdated and not sure anyone will take it on

**Comment by RobJohnston** [comment] 2016-11-14 14:04
Maybe this can be closed as a duplicate of #27 .

**Comment by RobJohnston** [comment] 2016-11-17 01:26
Found a way forward from another issue:  [Note to all developers - You can now upgrade to Node v0.12] (https://github.com/wet-boew/wet-boew/issues/6964).  Looks like node v0.12 couldn't be used until  grunt-sass": "^1.0.0".

 I had to downgrade to node v0.10 and then it finished.  Doesn't help with this issue as titled, but it's a start.

Maybe, since nobody is updating this, the easiest thing to do is to update the docs.  Specifically the section ["I want to customize WET and design a new WET theme"] (http://wet-boew.github.io/wet-boew/docs/start-en.html#theme) should be updated to state the node version that works?

**Comment by nschonni** [comment] 2016-11-22 22:56
Closing as dupe

**Closed by nschonni** 2016-11-22 22:56 UTC
Labels: bug
